# ============================================================================
# Copyright (c) 2011, SuperKablamo, LLC.
# All rights reserved.
# info@superkablamo.com
#
# monster.py 
# ============================================================================

############################# SK IMPORTS #####################################
############################################################################## 
import models
import utils

from settings import *

############################# GAE IMPORTS ####################################
##############################################################################
import os
import logging

from django.utils import simplejson
from google.appengine.ext import db

######################## METHODS #############################################
##############################################################################
def getJSONMonster(monster):
    logging.info(TRACE+'getMonsterJSON()')
    json = monster.json
    json['id'] = monster.key().id()
    json['npc_id'] = monster.npc.key().id()
    return json
    
######################## DATA ################################################
##############################################################################   
MONSTER_DATA = [

  ################################# LEVEL 1 ##################################

  {'name': 'Kobold Minion',
  'role': models.MIN, 
  'challenge': models.STAN,   
  'level': 1,
  'race': 'Kobold',
  'alignment': 'Evil',
  'size': 'Small',
  'experience': 25,
  'speed': 6,
  'items': [],
  'actions': 
    {'weapons': 
      [{'name': 'Javelin',
      'attack_mod': 5,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 0,
      'damage_mod': 4,
      'damage_keywords': [],
      'category': 'Simple Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False
      }],
    'powers': [],
    'heal': []},
  'hit_points': {'hp': 1},
  'scores': 
    {'abilities': 
      {'STR': {'score': 8, 'mod': -1}, 
      'CON': {'score': 12, 'mod': 1}, 
      'DEX': {'score': 16, 'mod': 3}, 
      'INT': {'score': 9, 'mod': -1}, 
      'WIS': {'score': 12, 'mod': 1}, 
      'CHA': {'score': 10, 'mod': 0}},
    'defenses': 
      {'AC': {'score': 15},
      'FORT': {'score': 11},
      'REF': {'score': 13},
      'WILL': {'score': 11}}},      
  'description': 'Kobolds are short, reptilian humanoids with cowardly and sadistic tendencies.  A kobold\'s scaly skin ranges from dark rusty brown to a rusty black color. It has glowing red eyes. Its tail is nonprehensile. Kobolds wear ragged clothing, favoring red and orange. A kobold is 2 to 2.5 feet tall and weighs 35 to 45 pounds. Kobolds speak Draconic with a voice that sounds like that of a yapping dog.',             
  'origin': 'Natural',
  'category': 'Humanoid',
  'languages': ['Common', 'Draconic'],
  'keywords': []},
 
  {'name': 'Kobold Warrior',
  'role': models.SKI,
  'challenge': models.STAN,        
  'level': 1,
  'race': 'Kobold',
  'alignment': 'Evil',
  'size': 'Small',
  'experience': 100,
  'speed': 6,
  'actions': 
    {'weapons': 
      [{'name': 'Spear',
      'attack_mod': 6,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 8,
      'damage_mod': 0,
      'damage_keywords': [],
      'category': 'Simple Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False}],
    'powers': [],
    'heal': []},
  'hit_points': {'hp': 27},
  'scores': 
    {'abilities': 
      {'STR': {'score': 8, 'mod': -1}, 
      'CON': {'score': 11, 'mod': 0}, 
      'DEX': {'score': 16, 'mod': 3}, 
      'INT': {'score': 6, 'mod': -2}, 
      'WIS': {'score': 10, 'mod': 0}, 
      'CHA': {'score': 15, 'mod': 2}},
    'defenses': 
      {'AC': {'score': 15},
      'FORT': {'score': 11},
      'REF': {'score': 14},
      'WILL': {'score': 13}}},   
  'description': 'Kobolds are short, reptilian humanoids with cowardly and sadistic tendencies.  A kobold\'s scaly skin ranges from dark rusty brown to a rusty black color. It has glowing red eyes. Its tail is nonprehensile. Kobolds wear ragged clothing, favoring red and orange. A kobold is 2 to 2.5 feet tall and weighs 35 to 45 pounds. Kobolds speak Draconic with a voice that sounds like that of a yapping dog.',             
  'origin': 'Natural',
  'category': 'Humanoid',
  'languages': ['Common', 'Draconic'],
  'keywords': []},
  
  {'name': 'Kobold Wyrmpriest',
  'role': models.ART, 
  'challenge': models.LEAD,   
  'level': 3,
  'race': 'Kobold',
  'alignment': 'Evil',
  'size': 'Small',
  'experience': 150,
  'speed': 6,
  'items': [],
  'actions': 
    {'weapons': 
      [{'name': 'Spear',
      'attack_mod': 7,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 8,
      'damage_mod': 0,
      'damage_keywords': [],
      'category': 'Simple Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False}],
    'powers': 
      [{'name': 'Dragon Breath',
      'recharge': 86400,
      'source_keyword': 'Racial',
      'accessory_keyword': None,
      'damage_keywords': ['Fire'],     
      'effect_keyword': None,
      'attack_range': 30,
      'max_targets': 3,
      'max_attacks': 1,
      'attack_mod': 6,
      'defense_ability': 'FORT',
      'damage_dice': 1,  
      'damage_die': 10,   
      'damage_mod': 3},
      {'name': 'Energy Orb',
      'recharge': 10,
      'source_keyword': 'Arcane',
      'accessory_keyword': 'Implement',
      'damage_keywords': ['Fire'],     
      'effect_keyword': None,
      'attack_range': 60,
      'max_targets': 1,
      'max_attacks': 1,
      'attack_mod': 6,
      'defense_ability': 'REF',
      'damage_dice': 1,  
      'damage_die': 10,   
      'damage_mod': 3}],                 
    'heal': []},
  'hit_points': {'hp': 36},
  'scores': 
    {'abilities': 
      {'STR': {'score': 9, 'mod': 0}, 
      'CON': {'score': 12, 'mod': 2}, 
      'DEX': {'score': 16, 'mod': 4}, 
      'INT': {'score': 9, 'mod': 0}, 
      'WIS': {'score': 17, 'mod': 4}, 
      'CHA': {'score': 12, 'mod': 2}},
    'defenses': 
      {'AC': {'score': 17},
      'FORT': {'score': 13},
      'REF': {'score': 15},
      'WILL': {'score': 15}}},      
  'description': 'Kobolds are short, reptilian humanoids with cowardly and sadistic tendencies.  A kobold\'s scaly skin ranges from dark rusty brown to a rusty black color. It has glowing red eyes. Its tail is nonprehensile. Kobolds wear ragged clothing, favoring red and orange. A kobold is 2 to 2.5 feet tall and weighs 35 to 45 pounds. Kobolds speak Draconic with a voice that sounds like that of a yapping dog.',             
  'origin': 'Natural',
  'category': 'Humanoid',
  'languages': ['Common', 'Draconic'],
  'keywords': []},

  {'name': 'Goblin Cutter',
  'role': models.MIN,
  'challenge': models.STAN,        
  'level': 1,
  'race': 'Goblin',
  'alignment': 'Evil',
  'size': 'Small',
  'experience': 25,
  'speed': 6,
  'actions': 
    {'weapons': 
      [{'name': 'Shortsword',
      'attack_mod': 5,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 0,
      'damage_mod': 4,
      'damage_keywords': [],
      'category': 'Simple Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False}],
    'powers': [],
    'heal': []},
  'hit_points': {'hp': 1},
  'scores': 
    {'abilities': 
      {'STR': {'score': 14, 'mod': 2}, 
      'CON': {'score': 13, 'mod': 1}, 
      'DEX': {'score': 17, 'mod': 3}, 
      'INT': {'score': 8, 'mod': -1}, 
      'WIS': {'score': 12, 'mod': 1}, 
      'CHA': {'score': 8, 'mod': -1}},
    'defenses': 
      {'AC': {'score': 16},
      'FORT': {'score': 12},
      'REF': {'score': 14},
      'WILL': {'score': 11}}},   
  'description': 'A goblin stands 3 to 3.5 feet tall and weigh 40 to 45 pounds. Its eyes are usually dull and glazed, varying in color from red to yellow. A goblin\'s skin color ranges from yellow through any shade of orange to a deep red; usually all members of a single tribe are about the same color. Goblins wear clothing of dark leather, tending toward drab, soiled-looking colors. Goblins speak Goblin; those with Intelligence scores of 12 or higher also speak Common.',             
  'origin': 'Natural',
  'category': 'Humanoid',
  'languages': ['Common', 'Goblin'],
  'keywords': []},     

  {'name': 'Goblin Hexer',
  'role': models.CON,
  'challenge': models.LEAD,        
  'level': 3,
  'race': 'Goblin',
  'alignment': 'Evil',
  'size': 'Small',
  'experience': 150,
  'speed': 6,
  'actions': 
    {'weapons': 
      [{'name': 'Hexer Rod',
      'attack_mod': 7,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 6,
      'damage_mod': 1,
      'damage_keywords': [],
      'category': 'Simple Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False}],
    'powers': 
      [{'name': 'Blinding Hex',
      'recharge': 10,
      'source_keyword': 'Arcane',
      'accessory_keyword': 'Implement',
      'damage_keywords': [],     
      'effect_keyword': None,
      'attack_range': 60,
      'max_targets': 1,
      'max_attacks': 1,
      'attack_mod': 7,
      'defense_ability': 'FORT',
      'damage_dice': 2,  
      'damage_die': 6,   
      'damage_mod': 1},
      {'name': 'Stinging Hex',
      'recharge': 3600,
      'source_keyword': 'Arcane',
      'accessory_keyword': 'Implement',
      'damage_keywords': [],     
      'effect_keyword': None,
      'attack_range': 60,
      'max_targets': 1,
      'max_attacks': 1,
      'attack_mod': 7,
      'defense_ability': 'WILL',
      'damage_dice': 3,  
      'damage_die': 6,   
      'damage_mod': 1}],
    'heal': []},
  'hit_points': {'hp': 46},
  'scores': 
    {'abilities': 
      {'STR': {'score': 10, 'mod': 1}, 
      'CON': {'score': 14, 'mod': 3}, 
      'DEX': {'score': 15, 'mod': 3}, 
      'INT': {'score': 9, 'mod': 0}, 
      'WIS': {'score': 13, 'mod': 2}, 
      'CHA': {'score': 18, 'mod': 5}},
    'defenses': 
      {'AC': {'score': 17},
      'FORT': {'score': 14},
      'REF': {'score': 15},
      'WILL': {'score': 16}}},   
  'description': 'A goblin stands 3 to 3.5 feet tall and weigh 40 to 45 pounds. Its eyes are usually dull and glazed, varying in color from red to yellow. A goblin\'s skin color ranges from yellow through any shade of orange to a deep red; usually all members of a single tribe are about the same color. Goblins wear clothing of dark leather, tending toward drab, soiled-looking colors. Goblins speak Goblin; those with Intelligence scores of 12 or higher also speak Common.',             
  'origin': 'Natural',
  'category': 'Humanoid',
  'languages': ['Common', 'Goblin'],
  'keywords': []},

  ################################# LEVEL 2 ##################################

  {'name': 'Decrepit Skeleton',
  'role': models.MIN,
  'challenge': models.STAN,        
  'level': 2,
  'race': 'Skeleton',
  'alignment': 'Unaligned',
  'size': 'Medium',
  'experience': 31,
  'speed': 6,
  'actions': 
    {'weapons': 
      [{'name': 'Longsword',
      'attack_mod': 6,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 0,
      'damage_mod': 5,
      'damage_keywords': [],
      'category': 'Military Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False},
      {'name': 'Shortbow',
      'attack_mod': 6,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 0,
      'damage_mod': 5,
      'damage_keywords': [],
      'category': 'Military Ranged',
      'short_range': 30,
      'long_range': 60,
      'magic': False}],
    'powers': [],
    'heal': []},
  'hit_points': {'hp': 1},
  'scores': 
    {'abilities': 
      {'STR': {'score': 15, 'mod': 2}, 
      'CON': {'score': 13, 'mod': 1}, 
      'DEX': {'score': 17, 'mod': 3}, 
      'INT': {'score': 3, 'mod': -4}, 
      'WIS': {'score': 14, 'mod': 2}, 
      'CHA': {'score': 3, 'mod': -4}},
    'defenses': 
      {'AC': {'score': 16},
      'FORT': {'score': 13},
      'REF': {'score': 14},
      'WILL': {'score': 13}}},   
  'description': 'Skeletons are the animated bones of the dead, mindless automatons that obey the orders of their evil masters.  A skeleton is seldom garbed in anything more than the rotting remnants of any clothing or armor it was wearing when slain.  A skeleton does only what it is ordered to do.  It can draw no conclusions of its own and takes no initiative.  Because of this limitation, its instructions must always be simple.  A skeleton attacks until destroyed.',             
  'origin': 'Natural',
  'category': 'Animate',
  'languages': [],     
  'keywords': ['Undead']},  

  {'name': 'Blazing Skeleton',
  'role': models.ART,
  'challenge': models.LEAD,        
  'level': 4,
  'race': 'Skeleton',
  'alignment': 'Unaligned',
  'size': 'Medium',
  'experience': 175,
  'speed': 6,
  'actions': 
    {'weapons': 
      [{'name': 'Flaming Sword',
      'attack_mod': 8,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 4,
      'damage_mod': 5,
      'damage_keywords': ['Fire'],
      'category': 'Military Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False}],
    'powers':   
      [{'name': 'Flaming Orb',
      'recharge': 10,
      'source_keyword': 'Arcane',
      'accessory_keyword': None,
      'damage_keywords': ['Fire'],     
      'effect_keyword': None,
      'attack_range': 30,
      'max_targets': 1,
      'max_attacks': 1,
      'attack_mod': 8,
      'defense_ability': 'REF',
      'damage_dice': 2,  
      'damage_die': 4,   
      'damage_mod': 4}],
    'heal': []},
  'immunities': ['Disease', 'Poison'],
  'resist': {'Fire': 10, 'Necrotic': 10},
  'vulnerable': {'Radiant': 5},    
  'hit_points': {'hp': 48},
  'scores': 
    {'abilities': 
      {'STR': {'score': 13, 'mod': 3}, 
      'CON': {'score': 17, 'mod': 5}, 
      'DEX': {'score': 18, 'mod': 6}, 
      'INT': {'score': 4, 'mod': -1}, 
      'WIS': {'score': 15, 'mod': 4}, 
      'CHA': {'score': 6, 'mod': 0}},
    'defenses': 
      {'AC': {'score': 18},
      'FORT': {'score': 15},
      'REF': {'score': 17},
      'WILL': {'score': 15}}},   
  'description': 'Skeletons are the animated bones of the dead, mindless automatons that obey the orders of their evil masters.  A skeleton is seldom garbed in anything more than the rotting remnants of any clothing or armor it was wearing when slain.  A skeleton does only what it is ordered to do.  It can draw no conclusions of its own and takes no initiative.  Because of this limitation, its instructions must always be simple.  A skeleton attacks until destroyed.',             
  'origin': 'Natural',
  'category': 'Animate',
  'languages': [],     
  'keywords': ['Undead']},  

  {'name': 'Goblin Sharpshooter',
  'role': models.ART,
  'challenge': models.STAN,        
  'level': 2,
  'race': 'Goblin',
  'alignment': 'Evil',
  'size': 'Small',
  'experience': 125,
  'speed': 6,
  'actions': 
    {'weapons': 
      [{'name': 'Shortsword',
      'attack_mod': 6,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 6,
      'damage_mod': 2,
      'damage_keywords': [],
      'category': 'Simple Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False},
      {'name': 'Hand Crossbow',
      'attack_mod': 9,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 6,
      'damage_mod': 4,
      'damage_keywords': [],
      'category': 'Simple Ranged',
      'short_range': 30,
      'long_range': 60,
      'magic': False}],
    'powers': [],
    'heal': []},
  'hit_points': {'hp': 31},
  'scores': 
    {'abilities': 
      {'STR': {'score': 14, 'mod': 3}, 
      'CON': {'score': 13, 'mod': 2}, 
      'DEX': {'score': 18, 'mod': 5}, 
      'INT': {'score': 8, 'mod': 0}, 
      'WIS': {'score': 13, 'mod': 2}, 
      'CHA': {'score': 8, 'mod': 0}},
    'defenses': 
      {'AC': {'score': 16},
      'FORT': {'score': 12},
      'REF': {'score': 14},
      'WILL': {'score': 11}}},   
  'description': 'A goblin stands 3 to 3.5 feet tall and weigh 40 to 45 pounds. Its eyes are usually dull and glazed, varying in color from red to yellow. A goblin\'s skin color ranges from yellow through any shade of orange to a deep red; usually all members of a single tribe are about the same color. Goblins wear clothing of dark leather, tending toward drab, soiled-looking colors. Goblins speak Goblin; those with Intelligence scores of 12 or higher also speak Common.',             
  'origin': 'Natural',
  'category': 'Humanoid',
  'languages': ['Common', 'Goblin'],
  'keywords': []},     
  
  {'name': 'Wolf',
  'role': models.SKI,
  'challenge': models.STAN,        
  'level': 2,
  'race': 'Wolf',
  'alignment': 'Unaligned',
  'size': 'Medium',
  'experience': 125,
  'speed': 8,
  'actions': 
    {'weapons': 
      [{'name': 'Bite',
      'attack_mod': 7,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 6,
      'damage_mod': 2,
      'damage_keywords': [],
      'category': 'Unarmed Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False}],
    'powers': [],
    'heal': []},
  'hit_points': {'hp': 38},
  'scores': 
    {'abilities': 
      {'STR': {'score': 13, 'mod': 2}, 
      'CON': {'score': 14, 'mod': 3}, 
      'DEX': {'score': 14, 'mod': 3}, 
      'INT': {'score': 2, 'mod': -3}, 
      'WIS': {'score': 13, 'mod': 2}, 
      'CHA': {'score': 10, 'mod': 1}},
    'defenses': 
      {'AC': {'score': 16},
      'FORT': {'score': 14},
      'REF': {'score': 14},
      'WILL': {'score': 13}}},   
  'description': 'A gray wolf grows about 5 feet long and stands about 2.5 feet at the shoulder. It weighs about 200 pounds.',             
  'origin': 'Natural',
  'category': 'Beast',
  'languages': [],
  'keywords': []},  

  {'name': 'Kobold Dragonshield',
  'role': models.SOL, 
  'challenge': models.STAN,   
  'level': 2,
  'race': 'Kobold',
  'alignment': 'Evil',
  'size': 'Small',
  'experience': 125,
  'speed': 5,
  'items': [],
  'actions': 
    {'weapons': 
      [{'name': 'Shortsword',
      'attack_mod': 7,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 6,
      'damage_mod': 3,
      'damage_keywords': [],
      'category': 'Simple Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False
      }],
    'powers': [],
    'heal': []},
  'resist': {'Fire': 5}, 
  'hit_points': {'hp': 36},
  'scores': 
    {'abilities': 
      {'STR': {'score': 14, 'mod': 3}, 
      'CON': {'score': 12, 'mod': 2}, 
      'DEX': {'score': 13, 'mod': 2}, 
      'INT': {'score': 9, 'mod': 0}, 
      'WIS': {'score': 12, 'mod': 2}, 
      'CHA': {'score': 10, 'mod': 1}},
    'defenses': 
      {'AC': {'score': 18},
      'FORT': {'score': 14},
      'REF': {'score': 13},
      'WILL': {'score': 13}}},      
  'description': 'Kobolds are short, reptilian humanoids with cowardly and sadistic tendencies.  A kobold\'s scaly skin ranges from dark rusty brown to a rusty black color. It has glowing red eyes. Its tail is nonprehensile. Kobolds wear ragged clothing, favoring red and orange. A kobold is 2 to 2.5 feet tall and weighs 35 to 45 pounds. Kobolds speak Draconic with a voice that sounds like that of a yapping dog.',             
  'origin': 'Natural',
  'category': 'Humanoid',
  'languages': ['Common', 'Draconic'],
  'keywords': []},     

  ################################# LEVEL 3 ##################################

  {'name': 'Zombie',
  'role': models.MIN, 
  'challenge': models.STAN,   
  'level': 3,
  'race': 'Zombie',
  'alignment': 'Unaligned',
  'size': 'Medium',
  'experience': 38,
  'speed': 4,
  'items': [],
  'actions': 
    {'weapons': 
      [{'name': 'Bite',
      'attack_mod': 6,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 0,
      'damage_mod': 5,
      'damage_keywords': [],
      'category': 'Unarmed Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False
      }],
    'powers': [],
    'heal': []},
  'immunities': ['Disease', 'Poison'],
  'hit_points': {'hp': 1},
  'scores': 
    {'abilities': 
      {'STR': {'score': 14, 'mod': 2}, 
      'CON': {'score': 10, 'mod': 0}, 
      'DEX': {'score': 6, 'mod': -2}, 
      'INT': {'score': 1, 'mod': -5}, 
      'WIS': {'score': 8, 'mod': -1}, 
      'CHA': {'score': 3, 'mod': -4}},
    'defenses': 
      {'AC': {'score': 13},
      'FORT': {'score': 13},
      'REF': {'score': 9},
      'WILL': {'score': 10}}},      
  'description': 'Zombies are corpses reanimated through dark and sinister magic.',             
  'origin': 'Natural',
  'category': 'Animate',
  'languages': [],
  'keywords': ['Undead']},

  {'name': 'Zombie Rotking',
  'role': models.SOL, 
  'challenge': models.LEAD,   
  'level': 5,
  'race': 'Zombie',
  'alignment': 'Unaligned',
  'size': 'Medium',
  'experience': 200,
  'speed': 4,
  'items': [],
  'actions': 
    {'weapons': 
      [{'name': 'Bite',
      'attack_mod': 11,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 6,
      'damage_mod': 4,
      'damage_keywords': ['Cold'],
      'category': 'Unarmed Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False
      }],
    'powers': 
      [{'name': 'Deaths Breath',
      'recharge': 10,
      'source_keyword': 'Arcane',
      'accessory_keyword': None,
      'damage_keywords': ['Cold'],     
      'effect_keyword': None,
      'attack_range': 10,
      'max_targets': 2,
      'max_attacks': 1,
      'attack_mod': 9,
      'defense_ability': 'FORT',
      'damage_dice': 2,  
      'damage_die': 6,   
      'damage_mod': 2}],
    'heal': []},
  'immunities': ['Disease', 'Poison'],
  'resist': {'Cold': 10, 'Necrotic': 10},
  'vulnerable': {'Radiant': 5, 'Fire': 5},
  'hit_points': {'hp': 62},
  'scores': 
    {'abilities': 
      {'STR': {'score': 18, 'mod': 6}, 
      'CON': {'score': 15, 'mod': 5}, 
      'DEX': {'score': 10, 'mod': 3}, 
      'INT': {'score': 2, 'mod': -1}, 
      'WIS': {'score': 10, 'mod': 3}, 
      'CHA': {'score': 6, 'mod': 1}},
    'defenses': 
      {'AC': {'score': 20},
      'FORT': {'score': 18},
      'REF': {'score': 14},
      'WILL': {'score': 16}}},      
  'description': 'Zombies are corpses reanimated through dark and sinister magic.',             
  'origin': 'Natural',
  'category': 'Animate',
  'languages': [],
  'keywords': ['Undead']},

  {'name': 'Young White Dragon',
  'role': models.BRU,
  'challenge': models.SOLO,        
  'level': 3,
  'race': 'Dragon',
  'alignment': 'Evil',
  'size': 'Large',
  'experience': 750,
  'speed': 8,
  'actions': 
    {'weapons': 
      [{'name': 'Bite',
      'attack_mod': 6,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 8,
      'damage_mod': 6,
      'damage_keywords': ['Cold'],
      'category': 'Unarmed Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False},
      {'name': 'Claw',
      'attack_mod': 6,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 8,
      'damage_mod': 4,
      'damage_keywords': [],
      'category': 'Unarmed Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False}],
    'powers': 
      [{'name': 'Breath of Frost',
      'recharge': 3600,
      'source_keyword': 'Arcane',
      'accessory_keyword': None,
      'damage_keywords': ['Cold'],     
      'effect_keyword': None,
      'attack_range': 30,
      'max_targets': 3,
      'max_attacks': 1,
      'attack_mod': 4,
      'defense_ability': 'REF',
      'damage_dice': 3,  
      'damage_die': 6,   
      'damage_mod': 4}],
    'heal': []},
  'resist': {'Cold': 15},
  'hit_points': {'hp': 200},
  'scores': 
    {'abilities': 
      {'STR': {'score': 18, 'mod': 5}, 
      'CON': {'score': 18, 'mod': 5}, 
      'DEX': {'score': 10, 'mod': 1}, 
      'INT': {'score': 10, 'mod': 1}, 
      'WIS': {'score': 12, 'mod': 2}, 
      'CHA': {'score': 8, 'mod': 0}},
    'defenses': 
      {'AC': {'score': 18},
      'FORT': {'score': 20},
      'REF': {'score': 16},
      'WILL': {'score': 17}}},   
  'description': 'The scales of a wyrmling white dragon glisten like mirrors. As the dragon ages, the sheen disappears, and by very old age, scales of pale blue and light gray are mixed in with the white.',             
  'origin': 'Natural',
  'category': 'Magical Beast',
  'languages': ['Draconic'],     
  'keywords': ['Dragon']},

  {'name': 'Hobgoblin Archer',
  'role': models.ART,
  'challenge': models.STAN,        
  'level': 3,
  'race': 'Goblin',
  'alignment': 'Evil',
  'size': 'Small',
  'experience': 150,
  'speed': 6,
  'actions': 
    {'weapons': 
      [{'name': 'Longsword',
      'attack_mod': 6,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 8,
      'damage_mod': 2,
      'damage_keywords': [],
      'category': 'Military Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False},
      {'name': 'Long Bow',
      'attack_mod': 9,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 10,
      'damage_mod': 4,
      'damage_keywords': [],
      'category': 'Military Ranged',
      'short_range': 30,
      'long_range': 60,
      'magic': False}],
    'powers': [],
    'heal': []},
  'hit_points': {'hp': 39},
  'scores': 
    {'abilities': 
      {'STR': {'score': 14, 'mod': 3}, 
      'CON': {'score': 14, 'mod': 3}, 
      'DEX': {'score': 19, 'mod': 53}, 
      'INT': {'score': 11, 'mod': 1}, 
      'WIS': {'score': 14, 'mod': 3}, 
      'CHA': {'score': 10, 'mod': 1}},
    'defenses': 
      {'AC': {'score': 17},
      'FORT': {'score': 13},
      'REF': {'score': 15},
      'WILL': {'score': 13}}},   
  'description': 'A goblin stands 3 to 3.5 feet tall and weigh 40 to 45 pounds. Its eyes are usually dull and glazed, varying in color from red to yellow. A goblin\'s skin color ranges from yellow through any shade of orange to a deep red; usually all members of a single tribe are about the same color. Goblins wear clothing of dark leather, tending toward drab, soiled-looking colors. Goblins speak Goblin; those with Intelligence scores of 12 or higher also speak Common.',             
  'origin': 'Natural',
  'category': 'Humanoid',
  'languages': ['Common', 'Goblin'],
  'keywords': []},

  ################################# LEVEL 4 ##################################

  {'name': 'Orc',
  'role': models.MIN, 
  'challenge': models.STAN,   
  'level': 4,
  'race': 'Orc',
  'alignment': 'Chaotic Evil',
  'size': 'Medium',
  'experience': 44,
  'speed': 6,
  'items': [],
  'actions': 
    {'weapons': 
      [{'name': 'Club',
      'attack_mod': 9,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 0,
      'damage_mod': 5,
      'damage_keywords': [],
      'category': 'Simple Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False
      }],
    'powers': [],
    'heal': []},
  'hit_points': {'hp': 1},
  'scores': 
    {'abilities': 
      {'STR': {'score': 16, 'mod': 3}, 
      'CON': {'score': 14, 'mod': 2}, 
      'DEX': {'score': 10, 'mod': 0}, 
      'INT': {'score': 8, 'mod': -1}, 
      'WIS': {'score': 10, 'mod': 0}, 
      'CHA': {'score': 9, 'mod': -1}},
    'defenses': 
      {'AC': {'score': 16},
      'FORT': {'score': 15},
      'REF': {'score': 12},
      'WILL': {'score': 12}}},      
  'description': 'An orc\'s hair usually is black. It has lupine ears and reddish eyes. Orcs prefer wearing vivid colors that many humans would consider unpleasant, such as blood red, mustard yellow, yellow-green, and deep purple. Their equipment is dirty and unkempt. An adult male orc is a little over 6 feet tall and weighs about 210 pounds.',             
  'origin': 'Natural',
  'category': 'Humanoid',
  'languages': ['Common', 'Giant'],
  'keywords': []},

  {'name': 'Orc Champion',
  'role': models.BRU, 
  'challenge': models.LEAD,   
  'level': 6,
  'race': 'Orc',
  'alignment': 'Chaotic Evil',
  'size': 'Medium',
  'experience': 250,
  'speed': 6,
  'items': [],
  'actions': 
    {'weapons': 
      [{'name': 'Greataxe',
      'attack_mod': 11,
      'defense_ability': 'AC',
      'damage_dice': 2,
      'damage_die': 8,
      'damage_mod': 4,
      'damage_keywords': [],
      'category': 'Military Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False
      }],
    'powers': [],
    'heal': []},
  'hit_points': {'hp': 82},
  'scores': 
    {'abilities': 
      {'STR': {'score': 18, 'mod': 6}, 
      'CON': {'score': 17, 'mod': 5}, 
      'DEX': {'score': 15, 'mod': 4}, 
      'INT': {'score': 10, 'mod': 2}, 
      'WIS': {'score': 10, 'mod': 2}, 
      'CHA': {'score': 10, 'mod': 3}},
    'defenses': 
      {'AC': {'score': 20},
      'FORT': {'score': 18},
      'REF': {'score': 16},
      'WILL': {'score': 16}}},      
  'description': 'An orc\'s hair usually is black. It has lupine ears and reddish eyes. Orcs prefer wearing vivid colors that many humans would consider unpleasant, such as blood red, mustard yellow, yellow-green, and deep purple. Their equipment is dirty and unkempt. An adult male orc is a little over 6 feet tall and weighs about 210 pounds.',             
  'origin': 'Natural',
  'category': 'Humanoid',
  'languages': ['Common', 'Giant'],
  'keywords': []},
  
  {'name': 'Young Black Dragon',
  'role': models.LUR,
  'challenge': models.SOLO,        
  'level': 4,
  'race': 'Dragon',
  'alignment': 'Evil',
  'size': 'Large',
  'experience': 875,
  'speed': 8,
  'actions': 
    {'weapons': 
      [{'name': 'Bite',
      'attack_mod': 10,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 6,
      'damage_mod': 5,
      'damage_keywords': ['Acid'],
      'category': 'Unarmed Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False},
      {'name': 'Claw',
      'attack_mod': 8,
      'defense_ability': 'AC',
      'damage_dice': 2,
      'damage_die': 4,
      'damage_mod': 6,
      'damage_keywords': [],
      'category': 'Unarmed Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False}],
    'powers': 
      [{'name': 'Breath of Acid',
      'recharge': 3600,
      'source_keyword': 'Arcane',
      'accessory_keyword': None,
      'damage_keywords': ['Acid'],     
      'effect_keyword': None,
      'attack_range': 30,
      'max_targets': 4,
      'max_attacks': 1,
      'attack_mod': 7,
      'defense_ability': 'REF',
      'damage_dice': 1,  
      'damage_die': 12,   
      'damage_mod': 5}],
    'heal': []},
  'resist': {'Acid': 15},
  'hit_points': {'hp': 224},
  'scores': 
    {'abilities': 
      {'STR': {'score': 16, 'mod': 5}, 
      'CON': {'score': 16, 'mod': 5}, 
      'DEX': {'score': 20, 'mod': 7}, 
      'INT': {'score': 12, 'mod': 3}, 
      'WIS': {'score': 15, 'mod': 4}, 
      'CHA': {'score': 10, 'mod': 2}},
    'defenses': 
      {'AC': {'score': 22},
      'FORT': {'score': 18},
      'REF': {'score': 20},
      'WILL': {'score': 17}}},   
  'description': 'Black dragon are sometimes known as skull dragons because of their skeletal faces. Adding to the skeletal impression is the gradual deterioration of the hide around the base of the horn and the cheekbones. This deterioration increases with age and does not harm the dragon. On hatching, a black dragon\'s scales are thin, small, and glossy. As the dragon ages, they become larger, thicker, and duller, helping it camouflage itself in swamps and marshes.  Black dragons are especially fond of coins. Older dragons sometimes capture and question humanoids about stockpiles of gold, silver, and platinum coins before killing them.',             
  'origin': 'Natural',
  'category': 'Magical Beast',
  'languages': ['Common', 'Draconic'],     
  'keywords': ['Dragon', 'Aquatic']},

  {'name': 'Monstrous Spider',
  'role': models.SKI,
  'challenge': models.STAN,        
  'level': 4,
  'race': 'Spider',
  'alignment': 'Unaligned',
  'size': 'Medium',
  'experience': 175,
  'speed': 6,
  'actions': 
    {'weapons': 
      [{'name': 'Bite',
      'attack_mod': 6,
      'defense_ability': 'AC',
      'damage_dice': 2,
      'damage_die': 6,
      'damage_mod': 3,
      'damage_keywords': ['Posion'],
      'category': 'Unarmed Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False}],
    'powers': [],
    'heal': []},
  'hit_points': {'hp': 55},
  'scores': 
    {'abilities': 
      {'STR': {'score': 17, 'mod': 5}, 
      'CON': {'score': 15, 'mod': 4}, 
      'DEX': {'score': 18, 'mod': 6}, 
      'INT': {'score': 1, 'mod': -3}, 
      'WIS': {'score': 14, 'mod': 4}, 
      'CHA': {'score': 8, 'mod': 1}},
    'defenses': 
      {'AC': {'score': 20},
      'FORT': {'score': 17},
      'REF': {'score': 18},
      'WILL': {'score': 16}}},   
  'description': 'Monstrous spiders are aggressive predators that use their poisonous bites to subdue or kill prey.',             
  'origin': 'Natural',
  'category': 'Beast',
  'languages': [],
  'keywords': ['Spider']},

  ################################# LEVEL 5 ##################################

  {'name': 'Vamnpire Spawn',
  'role': models.MIN, 
  'challenge': models.STAN,   
  'level': 5,
  'race': 'Undead',
  'alignment': 'Evil',
  'size': 'Medium',
  'experience': 50,
  'speed': 7,
  'items': [],
  'actions': 
    {'weapons': 
      [{'name': 'Claws',
      'attack_mod': 11,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 0,
      'damage_mod': 5,
      'damage_keywords': ['Necrotic'],
      'category': 'Unarmed Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False
      }],
    'powers': [],
    'heal': []},
  'immunities': ['Disease', 'Poison'],
  'resist': {'Necrotic': 5},
  'hit_points': {'hp': 1},
  'scores': 
    {'abilities': 
      {'STR': {'score': 14, 'mod': 5}, 
      'CON': {'score': 14, 'mod': 5}, 
      'DEX': {'score': 16, 'mod': 6}, 
      'INT': {'score': 10, 'mod': 3}, 
      'WIS': {'score': 12, 'mod': 4}, 
      'CHA': {'score': 14, 'mod': 5}},
    'defenses': 
      {'AC': {'score': 20},
      'FORT': {'score': 17},
      'REF': {'score': 18},
      'WILL': {'score': 17}}},      
  'description': 'Vampire spawn are undead creatures that come into being when vampires slay mortals. Like their creators, spawn remain bound to their coffins and to the soil of their graves. Vampire spawn appear much as they did in life, although their features are often hardened, with a predatory look. ',             
  'origin': 'Natural',
  'category': 'Humanoid',
  'languages': ['Common'],
  'keywords': []},

  {'name': 'Vampire Knight',
  'role': models.LUR, 
  'challenge': models.LEAD,   
  'level': 7,
  'race': 'Undead',
  'alignment': 'Evil',
  'size': 'Medium',
  'experience': 300,
  'speed': 6,
  'items': [],
  'actions': 
    {'weapons': 
      [{'name': 'Longsword',
      'attack_mod': 12,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 8,
      'damage_mod': 4,
      'damage_keywords': ['Necrotic'],
      'category': 'Military Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False
      }],
    'powers':   
      [{'name': 'Blood Drain',
      'recharge': 3600,
      'source_keyword': 'Divine',
      'accessory_keyword': None,
      'damage_keywords': [],     
      'effect_keyword': 'Heal',
      'attack_range': 0,
      'max_targets': 1,
      'max_attacks': 1,
      'attack_mod': 12,
      'defense_ability': 'FORT',
      'damage_dice': 3,  
      'damage_die': 8,   
      'damage_mod': 4},
      {'name': 'Stab of Night',
      'recharge': 3600,
      'source_keyword': 'Divine',
      'accessory_keyword': None,
      'damage_keywords': ['Necrotic'],     
      'effect_keyword': None,
      'attack_range': 0,
      'max_targets': 1,
      'max_attacks': 1,
      'attack_mod': 12,
      'defense_ability': 'FORT',
      'damage_dice': 2,  
      'damage_die': 8,   
      'damage_mod': 10}],
    'heal': 
        [{'name':'Second Wind',
        'recharge': 3600,
        'points': 20}]},
  'immunities': ['Disease', 'Poison'],
  'resist': {'Necrotic': 10},
  'vulnerable': {'Radiant': 10,},        
  'hit_points': {'hp': 80},
  'scores': 
    {'abilities': 
      {'STR': {'score': 18, 'mod': 7}, 
      'CON': {'score': 13, 'mod': 4}, 
      'DEX': {'score': 22, 'mod': 9}, 
      'INT': {'score': 14, 'mod': 5}, 
      'WIS': {'score': 13, 'mod': 4}, 
      'CHA': {'score': 16, 'mod': 6}},
    'defenses': 
      {'AC': {'score': 23},
      'FORT': {'score': 17},
      'REF': {'score': 19},
      'WILL': {'score': 17}}},      
  'description': 'Vampires appear just as they did in life, although their features are often hardened and feral, with the predatory look of wolves. Like liches, they often embrace finery and decadence and may assume the guise of nobility. Despite their human appearance, vampires can be easily recognized, for they cast no shadows and throw no reflections in mirrors.',             
  'origin': 'Natural',
  'category': 'Humanoid',
  'languages': ['Common', 'Elven'],
  'keywords': ['Undead']},

  {'name': 'Young Green Dragon',
  'role': models.SKI,
  'challenge': models.SOLO,        
  'level': 5,
  'race': 'Dragon',
  'alignment': 'Evil',
  'size': 'Large',
  'experience': 1000,
  'speed': 9,
  'actions': 
    {'weapons': 
      [{'name': 'Bite',
      'attack_mod': 10,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 8,
      'damage_mod': 5,
      'damage_keywords': ['Poison'],
      'category': 'Unarmed Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False},
      {'name': 'Claw',
      'attack_mod': 10,
      'defense_ability': 'AC',
      'damage_dice': 2,
      'damage_die': 6,
      'damage_mod': 5,
      'damage_keywords': [],
      'category': 'Unarmed Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False}],
    'powers': 
      [{'name': 'Breath of Poison',
      'recharge': 3600,
      'source_keyword': 'Arcane',
      'accessory_keyword': None,
      'damage_keywords': ['Poison'],     
      'effect_keyword': None,
      'attack_range': 30,
      'max_targets': 5,
      'max_attacks': 1,
      'attack_mod': 8,
      'defense_ability': 'FORT',
      'damage_dice': 1,  
      'damage_die': 10,   
      'damage_mod': 6}],
    'heal': []},
  'resist': {'Poison': 15},
  'hit_points': {'hp': 260},
  'scores': 
    {'abilities': 
      {'STR': {'score': 15, 'mod': 4}, 
      'CON': {'score': 17, 'mod': 5}, 
      'DEX': {'score': 20, 'mod': 7}, 
      'INT': {'score': 15, 'mod': 4}, 
      'WIS': {'score': 16, 'mod': 5}, 
      'CHA': {'score': 17, 'mod': 5}},
    'defenses': 
      {'AC': {'score': 21},
      'FORT': {'score': 17},
      'REF': {'score': 19},
      'WILL': {'score': 17}}},   
  'description': 'A wyrmling green dragon\'s scales are thin, very small, and a deep shade of green that appears nearly black. As the dragon ages, the scales grow larger and lighter, turning shades of forest, emerald, and olive green, which helps it blend in with its wooded surroundings.',             
  'origin': 'Natural',
  'category': 'Magical Beast',
  'languages': ['Common','Draconic'],     
  'keywords': ['Dragon']},
  
  {'name': 'Bugbear Warrior',
  'role': models.BRU,
  'challenge': models.STAN,        
  'level': 5,
  'race': 'Goblin',
  'alignment': 'Evil',
  'size': 'Medium',
  'experience': 200,
  'speed': 6,
  'actions': 
    {'weapons': 
      [{'name': 'Morningstar',
      'attack_mod': 7,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 12,
      'damage_mod': 6,
      'damage_keywords': [],
      'category': 'Simple Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False}],
    'powers': 
      [{'name': 'Skullthumper',
      'recharge': 3600,
      'source_keyword': 'Martial',
      'accessory_keyword': 'Weapon',
      'damage_keywords': [],     
      'effect_keyword': None,
      'attack_range': 0,
      'max_targets': 1,
      'max_attacks': 1,
      'attack_mod': 5,
      'defense_ability': 'FORT',
      'damage_dice': 1,  
      'damage_die': 12,   
      'damage_mod': 6}],
    'heal': []},
  'hit_points': {'hp': 76},
  'scores': 
    {'abilities': 
      {'STR': {'score': 20, 'mod': 7}, 
      'CON': {'score': 16, 'mod': 5}, 
      'DEX': {'score': 16, 'mod': 5}, 
      'INT': {'score': 10, 'mod': 2}, 
      'WIS': {'score': 14, 'mod': 4}, 
      'CHA': {'score': 10, 'mod': 2}},
    'defenses': 
      {'AC': {'score': 18},
      'FORT': {'score': 17},
      'REF': {'score': 15},
      'WILL': {'score': 14}}},   
  'description': 'Bugbears are big, tough Goblins.',             
  'origin': 'Natural',
  'category': 'Humanoid',
  'languages': ['Common', 'Goblin'],
  'keywords': []},   

  ################################# LEVEL X ##################################

  {'name': 'Hill Giant',
  'role': models.BRU,
  'challenge': models.STAN,        
  'level': 13,
  'race': 'Giant',
  'alignment': 'Chaotic Evil',
  'size': 'Large',
  'experience': 800,
  'speed': 8,
  'actions': 
    {'weapons': 
      [{'name': 'Greatclub',
      'attack_mod': 15,
      'defense_ability': 'AC',
      'damage_dice': 1,
      'damage_die': 10,
      'damage_mod': 5,
      'damage_keywords': [],
      'category': 'Simple Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False},
      {'name': 'Rock',
      'attack_mod': 15,
      'defense_ability': 'AC',
      'damage_dice': 2,
      'damage_die': 6,
      'damage_mod': 5,
      'damage_keywords': [],
      'category': 'Improvised Melee',
      'short_range': 30,
      'long_range': 60,
      'magic': False}],
    'powers': 
      [{'name': 'Sweeping Club',
      'recharge': 3600,
      'source_keyword': 'Martial',
      'accessory_keyword': 'Weapon',
      'damage_keywords': [],     
      'effect_keyword': None,
      'attack_range': 0,
      'max_targets': 2,
      'max_attacks': 1,
      'attack_mod': 15,
      'defense_ability': 'AC',
      'damage_dice': 1,  
      'damage_die': 10,   
      'damage_mod': 5}],
    'heal': []},
  'hit_points': {'hp': 159},
  'scores': 
    {'abilities': 
      {'STR': {'score': 21, 'mod': 11}, 
      'CON': {'score': 19, 'mod': 10}, 
      'DEX': {'score': 8, 'mod': 5}, 
      'INT': {'score': 7, 'mod': 4}, 
      'WIS': {'score': 12, 'mod': 7}, 
      'CHA': {'score': 9, 'mod': 5}},
    'defenses': 
      {'AC': {'score': 25},
      'FORT': {'score': 27},
      'REF': {'score': 21},
      'WILL': {'score': 23}}},   
  'description': 'Skin color among hill giants ranges from light tan to deep ruddy brown. Their hair is brown or black, with eyes the same color. Hill giants wear layers of crudely prepared hides with the fur left on. They seldom wash or repair their garments, preferring to simply add more hides as their old ones wear out. Adults are about 10.5 feet tall and weigh about 1,100 pounds. Hill giants can live to be 200 years old.',             
  'origin': 'Natural',
  'category': 'Humanoid',
  'languages': ['Giant'],     
  'keywords': ['Giant']},

  {'name': 'Adult Red Dragon',
  'role': models.SOL,
  'challenge': models.SOLO,        
  'level': 15,
  'race': 'Dragon',
  'alignment': 'Evil',
  'size': 'Large',
  'experience': 6000,
  'speed': 8,
  'actions': 
    {'weapons': 
      [{'name': 'Bite',
      'attack_mod': 22,
      'defense_ability': 'AC',
      'damage_dice': 5,
      'damage_die': 6,
      'damage_mod': 7,
      'damage_keywords': ['Fire'],
      'category': 'Unarmed Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False},
      {'name': 'Claw',
      'attack_mod': 22,
      'defense_ability': 'AC',
      'damage_dice': 2,
      'damage_die': 8,
      'damage_mod': 7,
      'damage_keywords': ['Fire'],
      'category': 'Unarmed Melee',
      'short_range': 0,
      'long_range': 0,
      'magic': False}],
    'powers': 
      [{'name': 'Breath of Fire',
      'recharge': 3600,
      'source_keyword': 'Arcane',
      'accessory_keyword': None,
      'damage_keywords': ['Fire'],     
      'effect_keyword': None,
      'attack_range': 30,
      'max_targets': 5,
      'max_attacks': 1,
      'attack_mod': 20,
      'defense_ability': 'REF',
      'damage_dice': 2,  
      'damage_die': 12,   
      'damage_mod': 6}],
    'heal': []},
  'hit_points': {'hp': 1},
  'scores': 
    {'abilities': 
      {'STR': {'score': 15, 'mod': 2}, 
      'CON': {'score': 13, 'mod': 1}, 
      'DEX': {'score': 17, 'mod': 3}, 
      'INT': {'score': 3, 'mod': -4}, 
      'WIS': {'score': 14, 'mod': 2}, 
      'CHA': {'score': 3, 'mod': -4}},
    'defenses': 
      {'AC': {'score': 16},
      'FORT': {'score': 13},
      'REF': {'score': 14},
      'WILL': {'score': 13}}},   
  'description': 'The small scales of a wyrmling red dragon are a bright glossy scarlet, making the dragon easily spotted by predators and hunters, so it stays underground and does not venture outside until it is more able to take care of itself. Toward the end of young age, the scales turn a deeper red, and the glossy texture is replaced by a smooth, dull finish. As the dragon grows older, the scales become large, thick, and as strong as metal. The neck frill and wings are an ash blue or purple-gray toward the edges, becoming darker with age. The pupils of a red dragon fade as it ages; the oldest red dragons have eyes that resemble molten lava orbs.',             
  'origin': 'Natural',
  'category': 'Magical Beast',
  'languages': ['Common', 'Draconic'],     
  'keywords': ['Dragon']}]
  