# ============================================================================
# Copyright (c) 2011, SuperKablamo, LLC.
# All rights reserved.
# info@superkablamo.com
#
# Powers.py defines the Data and Methods for providing Powers to the game 
# world.
#
# ============================================================================

############################# SK IMPORTS #####################################
############################################################################## 
from utils import roll

############################# GAE IMPORTS ####################################
##############################################################################
import logging

from random import choice

######################## METHODS #############################################
##############################################################################

######################## DATA ################################################
##############################################################################
ATTACK_DATA = [

  ############################## FIGHTER ATTACKS  ############################
    {'name': 'Lance of Faith',
     'casts': ['Cleric'],
     'level': 1,
     'description': 'A brilliant ray of light sears your foe with golden radiance.',
     'recharge': 10,
     'source_keyword': 'Divine',
     'accessory_keyword': 'Implement',
     'damage_keywords': ['Radiant'],
     'effect_keyword': None,
     'attack_range': 5,
     'max_targets': 1,
     'max_attacks': 1,
     'attack_ability': 'WIS',
     'attack_mod': 0,
     'defense_ability': 'REF',
     'damage_die': 8,
     'damage_dice': 1,
     'damage_weapon_multiplier': None,     
     'damage_ability_mod': 'WIS'},
    {'name': 'Priest\'s Shield',
     'casts': ['Cleric'],
     'level': 1,      
     'description': 'You utter a minor defensive prayer as you attack with your weapon.',      
     'recharge': 10,
     'source_keyword': 'Divine',
     'accessory_keyword': 'Weapon',
     'damage_keywords': [],
     'effect_keyword': None,      
     'attack_range': 0,
     'max_targets': 1,
     'max_attacks': 1,
     'attack_ability': 'STR',
     'attack_mod': 0,
     'defense_ability': 'AC',
     'damage_die': None,
     'damage_dice': None,
     'damage_weapon_multiplier': 1,
     'damage_ability_mod': 'STR'},
    {'name': 'Divine Glow',
     'casts': ['Cleric'],
     'level': 1,      
     'description': 'Murmuring a prayer to your diety, you invoke a blast of white radiance from you holy symbol.  Foes burn in its stern light.',      
     'recharge': 3600,
     'source_keyword': 'Divine',
     'accessory_keyword': 'Implement',
     'damage_keywords': ['Radiant'],
     'effect_keyword': None,      
     'attack_range': 5,
     'max_targets': 3,
     'max_attacks': 1,
     'attack_ability': 'WIS',
     'attack_mod': 0,
     'defense_ability': 'REF',
     'damage_die': 8,
     'damage_dice': 1,
     'damage_weapon_multiplier': None,     
     'damage_ability_mod': 'WIS'},
    {'name': 'Howling Strike',
     'casts': ['Barbarian'],
     'level': 1,      
     'description': 'With a blood-freezing scream, you throw yourelf into the fray.',      
     'recharge': 10,
     'source_keyword': 'Primal',
     'accessory_keyword': 'Weapon',
     'damage_keywords': [],    
     'effect_keyword': None,
     'attack_range': 0,
     'max_targets': 1,
     'max_attacks': 1,
     'attack_ability': 'STR',
     'attack_mod': 0,
     'defense_ability': 'AC',
     'damage_weapon_multiplier': 1,
     'damage_die': 6,
     'damage_dice': 1,     
     'damage_weapon_multiplier': None,      
     'damage_ability_mod': 'STR'},
    {'name': 'Vault the Fallen',
     'casts': ['Barbarian'],
     'level': 1,      
     'description': 'You leap from one foe to the next, leaving blood in your wake.',      
     'recharge': 3600,
     'source_keyword': 'Primal',
     'accessory_keyword': 'Weapon',
     'damage_keywords': [],    
     'effect_keyword': None,      
     'attack_range': 0,
     'max_targets': 2,
     'max_attacks': 1,
     'attack_ability': 'STR',
     'attack_mod': 0,
     'defense_ability': 'AC',
     'damage_weapon_multiplier': 1,
     'damage_die': 6,
     'damage_dice': 1, 
     'damage_weapon_multiplier': None,          
     'damage_ability_mod': 'STR'},
    {'name': 'Macetail\'s Rage',
     'casts': ['Barbarian'],
     'level': 1,      
     'description': 'You knock your enemy to the ground with a slam like the behemoth\'s heavy tail, and the rage of the macetail fills you, refreshing you with every blow of your weapon.',      
     'recharge': 86400,
     'source_keyword': 'Primal',
     'accessory_keyword': 'Weapon',
     'damage_keywords': [],    
     'effect_keyword': 'Rage',
     'attack_range': 0,
     'max_targets': 3,
     'max_attacks': 1,
     'attack_ability': 'STR',
     'attack_mod': 0,
     'defense_ability': 'REF',
     'damage_die': None,
     'damage_dice': None,     
     'damage_weapon_multiplier': 1,
     'damage_ability_mod': 'STR'},      
    {'name': 'Cleave',
     'casts': ['Fighter'],
     'level': 1,      
     'description': 'You hit one enemy, then cleave into another.',      
     'recharge': 10,
     'source_keyword': 'Martial',
     'accessory_keyword': 'Weapon',
     'damage_keywords': [],    
     'effect_keyword': None,
     'attack_range': 0,
     'max_targets': 2,
     'max_attacks': 1,
     'attack_ability': 'STR',
     'attack_mod': 0,
     'defense_ability': 'AC',
     'damage_die': None,
     'damage_dice': None,     
     'damage_weapon_multiplier': 1,
     'damage_ability_mod': 'STR'},
    {'name': 'Steel Serpent Strike',
     'casts': ['Fighter'],
     'level': 1,      
     'description': 'You stab viciously at your foe\'s knee of foot.  No matter how tough your foe is, they will favor that leg for some time.',      
     'recharge': 3600,
     'source_keyword': 'Martial',
     'accessory_keyword': 'Weapon',
     'damage_keywords': [],     
     'effect_keyword': None,
     'attack_range': 0,
     'max_targets': 1,
     'max_attacks': 1,
     'attack_ability': 'STR',
     'attack_mod': 0,
     'defense_ability': 'AC',
     'damage_die': None,
     'damage_dice': None,     
     'damage_weapon_multiplier': 2,
     'damage_ability_mod': 'STR'},
    {'name': 'Brute Strike',
     'casts': ['Fighter'],
     'level': 1,      
     'description': 'You shatter armor and bone with a ringing blow.',      
     'recharge': 86400,
     'source_keyword': 'Martial',
     'accessory_keyword': 'Weapon',
     'damage_keywords': [],
     'effect_keyword': 'Reliable',
     'attack_range': 0,
     'max_targets': 1,
     'max_attacks': 1,
     'attack_ability': 'STR',
     'attack_mod': 0,
     'defense_ability': 'AC',
     'damage_die': None,
     'damage_dice': None,     
     'damage_weapon_multiplier': 3,
     'damage_ability_mod': 'STR'},      
    {'name': 'Twin Strike',
     'casts': ['Ranger'],
     'level': 1,      
     'description': 'If the first attack doesn\'t kill it, the second one might.',      
     'recharge': 10,
     'source_keyword': 'Martial',
     'accessory_keyword': 'Weapon',
     'damage_keywords': [],     
     'effect_keyword': None,      
     'attack_range': 30,
     'max_targets': 1,
     'max_attacks': 2,
     'attack_ability': 'DEX',
     'attack_mod': 0,
     'defense_ability': 'AC',
     'damage_die': None,
     'damage_dice': None,     
     'damage_weapon_multiplier': 1,
     'damage_ability_mod': None},
    {'name': 'Dire Wolverine Strike',
     'casts': ['Ranger'],
     'level': 1,      
     'description': 'Enemies surround you -- much to their chagrin, as you slash them to pieces with the ferocity of a wounded dire wolverine.',      
     'recharge': 3600,
     'source_keyword': 'Martial',
     'accessory_keyword': 'Weapon',
     'damage_keywords': [],     
     'effect_keyword': None,      
     'attack_range': 0,
     'max_targets': 3,
     'max_attacks': 1,
     'attack_ability': 'STR',
     'attack_mod': 0,
     'defense_ability': 'AC',
     'damage_die': None,
     'damage_dice': None,     
     'damage_weapon_multiplier': 1,
     'damage_ability_mod': None},
    {'name': 'Hunter\'s Bear Trap',
     'casts': ['Ranger'],
     'level': 1,      
     'description': 'A well-placed shot to the leg leaves your enemy hobbled and bleeding.',      
     'recharge': 86400,
     'source_keyword': 'Martial',
     'accessory_keyword': 'Weapon',
     'damage_keywords': [],     
     'effect_keyword': None,
     'attack_range': 30,
     'max_targets': 1,
     'max_attacks': 1,
     'attack_ability': 'DEX',
     'attack_mod': 0,
     'defense_ability': 'AC',
     'damage_die': None,
     'damage_dice': None,     
     'damage_weapon_multiplier': 2,
     'damage_ability_mod': 'DEX'},
    {'name': 'Deft Strike',
     'casts': ['Rogue'],
     'level': 1,      
     'description': 'A final lunge brings you into an advantageous position.',      
     'recharge': 30,
     'source_keyword': 'Martial',
     'accessory_keyword': 'Weapon',
     'damage_keywords': [],     
     'effect_keyword': None,
     'attack_range': 0,
     'max_targets': 1,
     'max_attacks': 1,
     'attack_ability': 'DEX',
     'attack_mod': 0,
     'defense_ability': 'AC',
     'damage_die': None,
     'damage_dice': None,     
     'damage_weapon_multiplier': 1,
     'damage_ability_mod': 'DEX'},
    {'name': 'Torturous Strike',
     'casts': ['Rogue'],
     'level': 1,      
     'description': 'If you twist the blade in the wound just so, you can make your enemy howl in pain.',      
     'recharge': 3600,
     'source_keyword': 'Martial',
     'accessory_keyword': 'Weapon',
     'damage_keywords': [],     
     'effect_keyword': None,      
     'attack_range': 0,
     'max_targets': 1,
     'max_attacks': 1,
     'attack_ability': 'DEX',
     'attack_mod': 0,
     'defense_ability': 'AC',
     'damage_die': None,
     'damage_dice': None,     
     'damage_weapon_multiplier': 2,
     'damage_ability_mod': 'DEX'},  
    {'name': 'Trick Strike',
     'casts': ['Rogue'],
     'level': 1,      
     'description': 'Through a series of feints and lures, you maneuver your foe right where you want him.',      
     'recharge': 86400,
     'source_keyword': 'Martial',
     'accessory_keyword': 'Weapon',
     'damage_keywords': [],     
     'effect_keyword': None,      
     'attack_range': 0,
     'max_targets': 1,
     'max_attacks': 1,
     'attack_ability': 'DEX',
     'attack_mod': 0,
     'defense_ability': 'AC',
     'damage_die': None,
     'damage_dice': None,     
     'damage_weapon_multiplier': 3,
     'damage_ability_mod': 'DEX'},
    {'name': 'Magic Missile',
     'casts': ['Wizard'],
     'level': 1,      
     'description': 'You launch a silvery bolt of force at an enemy.',      
     'recharge': 30,
     'source_keyword': 'Arcane',
     'accessory_keyword': 'Implement',
     'damage_keywords': ['Force'],
     'effect_keyword': None,
     'attack_range': 30,
     'max_targets': 1,
     'max_attacks': 1,
     'attack_ability': 'INT',
     'attack_mod': 0,
     'defense_ability': 'REF',
     'damage_die': 4,
     'damage_dice': 2,
     'damage_weapon_multiplier': None,     
     'damage_ability_mod': 'INT'},
    {'name': 'Burning Hands',
     'casts': ['Wizard'],
     'level': 1,      
     'description': 'A fierce burst of flame erupts from your hands and scorches nearby foes.',      
     'recharge': 3600,
     'source_keyword': 'Arcane',
     'accessory_keyword': 'Implement',
     'damage_keywords': ['Fire'],
     'effect_keyword': None,
     'attack_range': 0,
     'max_targets': 5,
     'max_attacks': 1,
     'attack_ability': 'INT',
     'attack_mod': 0,
     'defense_ability': 'REF',
     'damage_die': 6,
     'damage_dice': 2,
     'damage_weapon_multiplier': None,     
     'damage_ability_mod': 'INT'},
    {'name': 'Acid Arrow',
     'casts': ['Wizard'],
     'level': 1,      
     'description': 'A shimmering arrow of green, glowing liquid streaks to your target and bursts in a spray of sizzling acid.',      
     'recharge': 86400,
     'source_keyword': 'Arcane',
     'accessory_keyword': 'Implement',
     'damage_keywords': ['Acid'],
     'effect_keyword': None,
     'attack_range': 30,
     'max_targets': 4,
     'max_attacks': 1,
     'attack_ability': 'INT',
     'attack_mod': 0,
     'defense_ability': 'REF',
     'damage_die': 8,
     'damage_dice': 2,
     'damage_weapon_multiplier': None,     
     'damage_ability_mod': 'INT'}]
     