application: superlarp-sk
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on

handlers:
- url: /api/.*
  script: api.py    

- url: /admin/.*
  script: admin.py
  login: admin

- url: /.*
  script: main.py

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico  
